-- 44 verified Yoga With Adriene classes. All video IDs confirmed live via YouTube oembed.
-- Distributed across day-themes so each Mon/Wed/Fri gets unique picks.
-- Run after schema.sql. Safe to re-run after a `delete from classes;`.

delete from classes;

insert into classes (title, instructor, youtube_url, duration_minutes, tags) values
  ('Yoga For Complete Beginners', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=v7AYKMP6rOE', 24, array['foundation','beginner']),
  ('Day 1 - Ease Into It (30 Days of Yoga)', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=oBu-pQG6sTY', 35, array['foundation','beginner','gentle']),
  ('Full Body Flow - 20 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=b1H3xO3x_Js', 19, array['full-body','flexibility']),
  ('Yoga For Anxiety and Stress', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=hJbRpHZr_d0', 25, array['gentle','restorative']),
  ('Total Body Yoga - Deep Stretch', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=GLy2rYHwUqY', 45, array['stretch','restorative','full-body']),
  ('Yoga For Neck, Shoulders, Upper Back', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=X3-gKPNyrTA', 11, array['mobility','back','spine']),
  ('Yoga at Your Desk', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=tAUf7aajBWE', 15, array['mobility','gentle']),
  ('Yoga for People Who Sit All Day', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=a-sZbOfau6c', 9, array['mobility','hips']),
  ('Yoga for Heavy Hearts', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=2akHh5GgzvM', 19, array['gentle','restorative']),
  ('Yoga for Neck Hump - Upper Spine Posture', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=n1E8aTKJmVg', 28, array['mobility','spine','back']),
  ('Yoga For When You Are Overstimulated', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=rPcBPTrPsgU', 17, array['restorative','gentle']),
  ('Mountain Flow - Hands Free Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=arydjHTU0iE', 10, array['balance','full-body']),
  ('Morning Yoga Flow - 20 Min Practice', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=LqXZ628YNj4', 22, array['morning','beginner','gentle']),
  ('Morning Yoga for Beginners - Gentle', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=GnHTeHAZQhM', 22, array['morning','beginner','gentle']),
  ('20 Min Yoga For Beginners - Start Here', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=vNyJuQuuMC8', 22, array['foundation','beginner']),
  ('Yoga For Beginners - A Little Goes a Long Way', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=M7JfqOfqSmI', 19, array['foundation','beginner']),
  ('Foundations of Flow', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=1p-ayBIRRHs', 20, array['foundation','beginner']),
  ('The BEST Way To Start Your Day - 10 Min Morning Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=klmBssEYkdU', 11, array['morning','gentle','beginner']),
  ('Early Morning Yoga and Meditation', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=mMSsHji8LDA', 20, array['morning','gentle']),
  ('Gentle, Relaxing, Cozy Flow - 20 Min Home Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=jHZPtn15agE', 21, array['gentle','beginner']),
  ('Yoga Flow For Beginners - Intro To Flow', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=4TLHLNX65-4', 25, array['foundation','beginner']),
  ('Upper Back and Neck Mobility - 13 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=mgpjd4JMSZg', 13, array['mobility','back','spine']),
  ('Hip Mobility - Open Your Hips', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=GffXQl3zvUI', 14, array['mobility','hips']),
  ('20 Min Yoga For Hips - Feel Good Flow', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=zwoVcrdmLOE', 24, array['hips','mobility']),
  ('Yoga For Hips & Lower Back Release', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=Ho9em79_0qg', 23, array['hips','back','mobility']),
  ('12 Min Core Conditioning', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=8T39OBNaNzU', 12, array['core','mobility']),
  ('Disciplined Core - 15 Min Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=yqRqRURB9IE', 15, array['core']),
  ('Yoga For Lower Back Pain', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=XeXz8fIZDCE', 16, array['back','mobility']),
  ('Yoga For Upper Back Pain', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=d6zJkHcjbWc', 12, array['back','spine','mobility']),
  ('Morning Mobility Yoga - Wake Up and Stretch', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=2IcWJobNDck', 22, array['mobility','morning']),
  ('Brain + Body Balance - 22 Min Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=XN3JB67-a_k', 23, array['balance','mobility']),
  ('Morning Hip Release - 15 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=u1qayo-0aL4', 15, array['hips','mobility','morning']),
  ('Yoga For Flexibility - 16 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=Yzm3fA2HhkQ', 16, array['flexibility','stretch']),
  ('10 Minute Full Body Stretch', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=lxuTCHJSers', 12, array['stretch','full-body','flexibility']),
  ('Yoga Stretch For Recovery Days - 12 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=KrUnq66qn_k', 12, array['stretch','restorative']),
  ('Bedtime Yoga - 20 Min Practice', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=v7SN-d4qXx0', 19, array['restorative','gentle']),
  ('Wind Down Yoga - 12 Min Bedtime', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=BiWDsfZ3zbo', 12, array['restorative','gentle']),
  ('Yoga Stretch', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=AF9d2Icl4fA', 21, array['stretch','flexibility','full-body']),
  ('Yoga For Hamstrings', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=-Mirm7LKvKk', 23, array['stretch','flexibility']),
  ('Yoga For Low Back and Hamstrings - 30 Min', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=2xF_teT2_V0', 29, array['stretch','flexibility','back']),
  ('Flow Into Stillness - 30 Min Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=PeWuJY7J2Gs', 30, array['restorative','full-body']),
  ('Yoga Flow - 20 Min Vinyasa Sequence', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=xmeNZI8inWI', 19, array['full-body','flexibility']),
  ('Fill Your Cup Yoga - 20 Min Home Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=H4dVbaLqg84', 21, array['full-body','gentle']),
  ('Yoga To Feel Your Best - 22 Min Home Yoga', 'Yoga With Adriene', 'https://www.youtube.com/watch?v=BPK9WNtpBgk', 23, array['full-body','gentle']);
